# Generated by Django 2.0.1 on 2018-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshsheet',
            name='body',
        ),
        migrations.RemoveField(
            model_name='freshsheet',
            name='title',
        ),
        migrations.AddField(
            model_name='freshsheet',
            name='farms',
            field=models.CharField(blank=True, choices=[('BH', 'Black Hills Organic Microgreens, Olympia, WA'), ('BY', 'Blazing Yarrow, Independence Valley, WA'), ('CA', 'Calliope Farm, Olympia, WA'), ('DR', 'Dharma Ridge, Olympia, WA'), ('HJ', 'Helsing Junction Farm, Independence Valley, WA'), ('HS', 'Humble Stump Farm, Shelton, WA'), ('RR', 'Rising River Farm, Independence Valley, WA'), ('SRM', 'Skokomish Ridge Mushroom Co-Op, Shelton, WA'), ('SVF', 'Skokomish Valley Farms, Shelton, WA'), ('SB', 'Spooner Berry Farms, Olympia, WA'), ('WC', 'Wobbly Cart Farm, Independence Valley, WA'), ('BC', 'Bloom Creek Cranberries, Little Rock, WA')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freshsheet',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freshsheet',
            name='unit',
            field=models.CharField(default='Pounds', max_length=20),
        ),
        migrations.AddField(
            model_name='freshsheet',
            name='vegetable',
            field=models.CharField(default='', max_length=40),
        ),
    ]
