# Generated by Django 2.0.1 on 2018-02-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0002_auto_20180205_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'Shopping'), ('P', 'Pending'), ('O', 'Out For Delivery'), ('D', 'Delivered')], default='Shopping', max_length=40),
        ),
    ]
