# Generated by Django 2.0.1 on 2018-01-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0003_auto_20180103_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
