# Generated by Django 2.0.1 on 2018-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0004_auto_20180103_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshsheet',
            name='items',
            field=models.ManyToManyField(to='freshsheet.Vegetable'),
        ),
    ]
