# Generated by Django 2.0.1 on 2018-01-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0005_freshsheet_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshsheet',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='freshsheet',
            name='unit',
        ),
    ]
