# Generated by Django 2.0.1 on 2018-01-03 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0006_auto_20180103_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshsheet',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
