# Generated by Django 2.0.1 on 2018-05-10 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0007_freshsheet_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date_added',
            field=models.DateField(auto_created=True, default=datetime.datetime(2018, 5, 10, 5, 7, 49, 441547, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
