# Generated by Django 2.0.1 on 2018-01-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0007_auto_20180103_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='farms',
            field=models.CharField(choices=[('G', 'Greens'), ('B', 'Beans'), ('A', 'Alliums'), ('CH', 'Chicories'), ('CA', 'Cabbage'), ('HF', 'Herbs/Flowers'), ('P', 'Potatoes'), ('R', 'Root Vegetables'), ('SS', 'Summer Squash'), ('WS', 'Winter Squash')], max_length=40, null=True),
        ),
    ]
