# Generated by Django 2.0.1 on 2018-05-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0008_fooditem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshsheet',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freshsheet',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
