# Generated by Django 2.0.1 on 2018-01-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0008_vegetable_farms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetable',
            old_name='farms',
            new_name='category',
        ),
    ]
