# Generated by Django 2.0.1 on 2018-01-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0009_auto_20180104_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
