# Generated by Django 2.0.1 on 2018-01-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0010_vegetable_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freshsheet',
            old_name='items',
            new_name='item_vegetable',
        ),
        migrations.AddField(
            model_name='freshsheet',
            name='item_farm',
            field=models.ManyToManyField(to='freshsheet.Farm'),
        ),
    ]
