# Generated by Django 2.0.1 on 2018-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0010_auto_20180523_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='split_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_color',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='case_count',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='case_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='wholesale_count',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='case_count',
            field=models.PositiveIntegerField(blank=True, default=12, null=True, verbose_name='Minimum quantity for case price'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='case_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Case Price'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='wholesale_count',
            field=models.PositiveIntegerField(blank=True, default=12, null=True, verbose_name='Minimum quantity for wholesale price'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Wholesale Price'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Price'),
        ),
    ]
