# Generated by Django 2.0.1 on 2018-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0011_auto_20180523_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='case_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Minimum quantity for case price'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='case_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Case Price'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='wholesale_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Minimum quantity for wholesale price'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Wholesale Price'),
        ),
    ]
