# Generated by Django 2.0.1 on 2018-01-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0011_auto_20180104_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshsheet',
            name='item_farm',
        ),
        migrations.RemoveField(
            model_name='freshsheet',
            name='item_vegetable',
        ),
    ]
