# Generated by Django 2.0.1 on 2018-07-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0012_auto_20180523_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=40, verbose_name='Business Name')),
                ('business_address', models.CharField(max_length=75, verbose_name='Business Address')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('customer_position', models.CharField(max_length=20, verbose_name='Title/Position')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
