# Generated by Django 2.0.1 on 2018-01-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0012_auto_20180104_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vegetables', to='freshsheet.Farm')),
            ],
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='farm',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
        migrations.AddField(
            model_name='freshsheet',
            name='items',
            field=models.ManyToManyField(to='freshsheet.FoodItem'),
        ),
    ]
