# Generated by Django 2.0.1 on 2018-07-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0013_accountrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='customer_position',
            field=models.CharField(max_length=20, verbose_name='Job Title'),
        ),
    ]
