# Generated by Django 2.0.1 on 2018-07-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0014_auto_20180702_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='account',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Type'),
        ),
    ]
