# Generated by Django 2.0.1 on 2018-01-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0015_auto_20180105_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
