# Generated by Django 2.0.1 on 2018-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0016_auto_20180105_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
    ]
