# Generated by Django 2.0.1 on 2018-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0016_auto_20180704_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Wholesale Price'),
        ),
    ]
