# Generated by Django 2.0.1 on 2018-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0017_auto_20180105_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_color',
            field=models.CharField(blank=True, choices=[('R', 'red'), ('OR', 'orange'), ('Y', 'yellow'), ('OL', 'olive'), ('G', 'green'), ('T', 'teal'), ('B', 'blue'), ('V', 'violet'), ('PU', 'purple'), ('PI', 'pink'), ('BR', 'brown'), ('G', 'grey'), ('BL', 'black')], default='', max_length=20, null=True),
        ),
    ]
