# Generated by Django 2.0.1 on 2018-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0017_auto_20180704_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='case_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Case Price'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Wholesale Price'),
        ),
    ]
