# Generated by Django 2.0.1 on 2018-01-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0019_auto_20180105_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='inventory',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(default='', max_length=15),
        ),
    ]
