# Generated by Django 2.0.1 on 2018-01-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0020_auto_20180108_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vegetables', to='freshsheet.Farm'),
        ),
    ]
