# Generated by Django 2.0.1 on 2018-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0023_auto_20180108_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(choices=[('LB', 'Pound(s)'), ('BU', 'Bundle'), ('HD', 'Head'), ('C', 'Count')], default=('LB', 'Pounds'), max_length=15),
        ),
    ]
