# Generated by Django 2.0.1 on 2018-01-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0024_auto_20180108_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vegetables/'),
        ),
    ]
