# Generated by Django 2.0.1 on 2018-10-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0025_fooditem_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='message_box',
            field=models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Please leave a message with your needs, questions, etc.'),
        ),
    ]
