# Generated by Django 2.0.1 on 2018-11-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0026_accountrequest_message_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='message_box',
            field=models.TextField(default='', max_length=5000, verbose_name='Message'),
        ),
    ]
