# Generated by Django 2.0.1 on 2018-11-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0028_auto_20181116_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qb_access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qb_refresh_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
