# Generated by Django 2.0.1 on 2018-11-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0029_auto_20181116_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qb_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qb_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
