# Generated by Django 2.0.1 on 2018-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0030_auto_20180108_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='manure',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_color',
            field=models.CharField(blank=True, choices=[('R', 'red'), ('OR', 'orange'), ('Y', 'yellow'), ('OL', 'olive'), ('GN', 'green'), ('T', 'teal'), ('B', 'blue'), ('V', 'violet'), ('PU', 'purple'), ('PI', 'pink'), ('BR', 'brown'), ('GR', 'grey'), ('BL', 'black'), ('WH', 'white')], default='', max_length=20, null=True),
        ),
    ]
