# Generated by Django 2.0.1 on 2018-01-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0031_auto_20180109_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='manure',
        ),
    ]
