# Generated by Django 2.0.1 on 2018-11-19 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0033_auto_20181117_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='req_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freshsheet.AccountRequest'),
        ),
    ]
