# Generated by Django 2.0.1 on 2018-11-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0034_user_req_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='business_city_st_zip',
            field=models.CharField(default='', max_length=75, verbose_name='City, State, Zip Code'),
        ),
    ]
