# Generated by Django 2.0.1 on 2018-01-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0035_remove_fooditem_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
