# Generated by Django 2.0.1 on 2018-11-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0036_auto_20181119_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrequest',
            old_name='business_city_st_zip',
            new_name='business_city',
        ),
    ]
