# Generated by Django 2.0.1 on 2018-11-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0038_user_qb_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qb_master_user',
            field=models.BooleanField(default=False),
        ),
    ]
