# Generated by Django 2.0.1 on 2018-11-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0039_user_qb_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qb_customer_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Quickbooks ID Number'),
        ),
    ]
