# Generated by Django 2.0.1 on 2018-12-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0040_auto_20181121_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qb_expires_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
