# Generated by Django 2.0.1 on 2019-01-14 22:46

from django.db import migrations, models
import django.db.models.deletion
import freshsheet.models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0042_auto_20190108_0000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', freshsheet.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='freshsheet_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='freshsheet.FreshSheet'),
        ),
    ]
