# Generated by Django 2.0.1 on 2019-01-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0043_auto_20190114_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='freshsheet_relation',
        ),
        migrations.AddField(
            model_name='order',
            name='freshsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='freshsheet.FreshSheet'),
        ),
    ]
