# Generated by Django 2.0.1 on 2019-01-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0044_auto_20190114_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='freshsheet',
        ),
    ]
