# Generated by Django 2.0.1 on 2019-01-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0046_order_freshsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_to',
            field=models.BooleanField(default=False),
        ),
    ]
