# Generated by Django 2.0.10 on 2019-01-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0047_user_email_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='message_box',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Message'),
        ),
    ]
