# Generated by Django 2.0.10 on 2019-01-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0048_auto_20190128_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
    ]
