# Generated by Django 2.0.10 on 2019-01-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0050_order_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='freshsheet',
        ),
    ]
