# Generated by Django 2.0.10 on 2019-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshsheet', '0052_order_freshsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshsheet',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
